name: Mirror Sync

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Push to mirror repo
        env:
          WEBSITE_MIRROR: ${{ secrets.WEBSITE_MIRROR }}
        run: |
          git remote add mirror https://x-access-token:${WEBSITE_MIRROR}@github.com/40476/40476.github.io.git
          git -c credential.helper= git push --mirror mirror
